<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_profile extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        // is_login();
        $this->load->model('User_dinas_model');
        $this->load->model('User_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $data['user']   =  $this->User_model->get_by_id($this->session->userdata('id_users'));
        $data['user_dinas'] = $this->User_dinas_model->get_by_id($data['user']->id_user_dinas);

        $this->template->load('template', 'user_profile/index',$data);
    }

    public function update_action($id)
    {
        $data = array(
            'NIK' => $this->input->post('nik'),
            'name' => $this->input->post('name'),
            'adress' => $this->input->post('adress'),
            'phone' => $this->input->post('phone'),
            'email' => $this->input->post('email'),
        );

        $user_dinas = $this->input->post('id_user_dinas');

        $data_user = array(
            'full_name' => $this->input->post('name'),
            'email' => $this->input->post('email'),
        );

        $this->User_model->update($id, $data_user);
        if($user_dinas != '' || $user_dinas != null || $user_dinas != 0) {
            $this->User_dinas_model->update($user_dinas, $data);
        }
        $this->session->set_flashdata('message', 'Update User Success');
        redirect(site_url('user_profile'));
    }

    
}

/* End of file User_dinas.php */
/* Location: ./application/controllers/User_dinas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-06 08:48:56 */
/* http://harviacode.com */