<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pph_sap_model extends CI_Model
{

    public $table = 'pph_sap';
    public $id = 'id1';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id1,document_number,year_month1,posting_key,document_header_text,account,acct_name,profit_center,document_date,posting_date,text,reference,amount_in_lc,vendor,name_cust_ven,reversed_with,cost_center,user_name,entry_date');
        $this->datatables->from('pph_sap');
        
        $kddivisi = $this->session->userdata('kodedivisi');
        //echo $kddivisi;
        //exit;
        if ($kddivisi != '')
        {
			if($kddivisi!="ALL")
			{
			$this->datatables->like('profit_center',substr($kddivisi,2));
			}
		}        
        
        //add this line for join
        //$this->datatables->join('table2', 'pph_sap.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pph_sap/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-info btn-xs', 'target' => '_blank'))." 
            ".anchor(site_url('pph_sap/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-xs'))." 
                ".anchor(site_url('pph_sap/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-xs" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id1');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id1', $q);
	$this->db->or_like('document_number', $q);
	$this->db->or_like('year_month1', $q);
	$this->db->or_like('posting_key', $q);
	$this->db->or_like('document_header_text', $q);
	$this->db->or_like('account', $q);
	$this->db->or_like('acct_name', $q);
	$this->db->or_like('profit_center', $q);
	$this->db->or_like('document_date', $q);
	$this->db->or_like('posting_date', $q);
	$this->db->or_like('text', $q);
	$this->db->or_like('reference', $q);
	$this->db->or_like('amount_in_lc', $q);
	$this->db->or_like('vendor', $q);
	$this->db->or_like('name_cust_ven', $q);
	$this->db->or_like('reversed_with', $q);
	$this->db->or_like('cost_center', $q);
	$this->db->or_like('user_name', $q);
	$this->db->or_like('entry_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id1', $q);
	$this->db->or_like('document_number', $q);
	$this->db->or_like('year_month1', $q);
	$this->db->or_like('posting_key', $q);
	$this->db->or_like('document_header_text', $q);
	$this->db->or_like('account', $q);
	$this->db->or_like('acct_name', $q);
	$this->db->or_like('profit_center', $q);
	$this->db->or_like('document_date', $q);
	$this->db->or_like('posting_date', $q);
	$this->db->or_like('text', $q);
	$this->db->or_like('reference', $q);
	$this->db->or_like('amount_in_lc', $q);
	$this->db->or_like('vendor', $q);
	$this->db->or_like('name_cust_ven', $q);
	$this->db->or_like('reversed_with', $q);
	$this->db->or_like('cost_center', $q);
	$this->db->or_like('user_name', $q);
	$this->db->or_like('entry_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pph_sap_model.php */
/* Location: ./application/models/Pph_sap_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-16 17:10:20 */
/* http://harviacode.com */
